modification du jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,22 +1,41 @@
 node {
+
     def app
 
-    stage('Clone') {
-        checkout scm
+    try {
+
+        stage('Clone') {
+            checkout scm
+        }
+
+        stage('Build image') {
+            app = docker.build("nassima/nginx")
+        }
+
+        stage('Run image') {
+
+            sh '''
+                docker run -d -p 8081:80 --name nginx_test nassima/nginx
+
+                echo "Waiting for nginx..."
+
+                for i in $(seq 1 30); do
+                    if curl -f http://localhost:8081; then
+                        echo "Nginx is UP"
+                        exit 0
+                    fi
+
+                    echo "Not ready yet... attempt $i"
+                    sleep 2
+                done
+
+                echo "Nginx failed"
+                docker logs nginx_test
+                exit 1
+            '''
+        }
+
+    } finally {
+        sh 'docker rm -f nginx_test || true'
     }
-
-    stage('Build image') {
-        app = docker.build("nassima/nginx")
-    }
-
-    stage('Run image') {
-    	docker.image('nassima/nginx').withRun('-p 8081:80') { c ->
-
-        	sh 'docker ps'
-
-        	sleep 5
-
-        	sh 'curl -f http://localhost:8081'
-    }
-} 
-}   
+}
